FROM multiarch/alpine:armhf-v3.9
LABEL "maintainer"="RandomK <randomk@foxmail.com>"

ENV TZ Asia/Shanghai

COPY etc/ /etc/
COPY root/ /root/

RUN echo 'https://mirrors.aliyun.com/alpine/v3.9/main' > /etc/apk/repositories \
    && echo 'https://mirrors.aliyun.com/alpine/v3.9/community' >> /etc/apk/repositories \
    && apk update && apk --no-cache add bash bash-completion curl vim tini tzdata

ENTRYPOINT ["tini", "--"]

CMD ["/bin/sh"]
